services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3333:4444
    volumes:
      - ./:/app
    env_file:
      - .env

  mysql_testtest:
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - mysql-data-test:/var/lib/mysql
    env_file:
      - .env

volumes:
  mysql-data-test:
