services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && node index.js"
    ports:
      - 3333:4444
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql_testtest
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DB: test

  mysql_testtest:
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - mysql-data-test:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: test

volumes:
  mysql-data-test:
